### PR TITLE
Replace T/F with TRUE/FALSE

### LINKED ISSUE #3: Lose any shortcut T or F's in the code
Based on https://github.com/hadley/strict I think we should remove any shortcuts using T/F!

### PR DESCRIPTION
**Pull request by KrishanBhasin**
I'd like to say I hacked together a long-winded bash command, but I used `Notepad++` find & replace 😆

closes #3 (sorry about getting you to close it early)

### CODE REVIEW

**Comment by KrishanBhasin** [comment]
I searched for `= T,` and `= T)` and replaced with `= TRUE,` and `= TRUE)`, and did the same for `F`/`FALSE`.

Are there any other kinds of ways T/F would be used?

**Comment by sajohnston** [comment]
There are some without spaces ('=F'), it looks like (in fact there's one in the same line as one your find/replace found!)

**Comment by sajohnston** [comment]
I know there's at least one more ( '= F ' with a space). Can you request to merge it into the dev branch instead of master?

**Comment by KrishanBhasin** [comment]
can do!

**Pull request closed without merging**
