### PR TITLE
Added Consistency of Capitalization in summary() Output

### PR DESCRIPTION
**Pull request by RjLi13**
## Description

Capitalized column names of missing columns to match with the case of other column names. Also changed _testMakeNames_ so that it would work with the capitalization fix.

## Motivation and Context

Fixes issue #40 

## How Has This Been Tested?

Ran existing tests, changing up testMakeNames so that it pass. Also, made sure to manually run the vignette workflow to visually verify it passes (check screenshot). This change does not affect the rest of the workflow other than the output of `summary`. 

## Screenshots (if appropriate):

This is the output of `summary` after my change.
new_output_summary

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by RjLi13** [comment]
Not sure why build times out. Tests are a bit slow, but pass on my end as well as package checks and builds successfully. Development environment:
                         
```
> version
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray 
```

**Comment by KrishanBhasin** [comment]
🎉

**Comment by RjLi13** [comment]
Thank you, looks like a reboot fixed the issue.

**Comment by rnobleeddy** [comment]
Thanks for the PR - looks good. 

Are you OK to sign the at contributor license agreement at https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform - this is required to make contributions back to Capital One projects. There are more details at the bottom of the README.

**Comment by RjLi13** [comment]
Hey Rob, I just filled out the form again.

**Comment by rnobleeddy** [comment]
Thanks - I'll check again. I'm going to try to fix a few of the other bugs, and will aim to wrap it all up as a release towards the end of August.

**Comment by rnobleeddy** [comment]
Sorry for the delay - I was looking at the wrong version of the form. I'll merge both PR's to `dev` now.

**Pull request merged**
