### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by KrishanBhasin**
## Description
Fix Travis CI

## Motivation and Context
All builds are currently failing, but due to a configuration error, not the R code

## How Has This Been Tested?
Checking Travis CI notes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by KrishanBhasin** [comment]
It's running the tests now, but with this error:

```
Running ‘testthat.R’

 ERROR

Running the tests in ‘tests/testthat.R’ failed.

Last 13 lines of output:

          return(matchNoIndex(df_a, df_b))

      }

      if (length(indices) == 1) {

          return(matchSingleIndex(df_a, df_b, indices))

      }

      if (length(indices) > 1) {

          return(matchMultiIndex(df_a, df_b, indices))

      }

  }

  <bytecode: 0x3653288>

  <environment: namespace:dataCompareR>

   --- function search by body ---

  Function matchRows in namespace dataCompareR has this body.

   ----------- END OF FAILURE REPORT -------------- 

```

**Comment by KrishanBhasin** [comment]
Full error log is collapsed below:

<details><summary>click here</summary>

```
----------- FAILURE REPORT -------------- 

 --- failure: length > 1 in coercion to logical ---

 --- srcref --- 

: 

 --- package (from environment) --- 

dataCompareR

 --- call from context --- 

matchRows(coerceData$DFA, coerceData$DFB, toupper(keys))

 --- call from argument --- 

length(indices == 1) && is.na(indices)

 --- R stacktrace ---

where 1: matchRows(coerceData$DFA, coerceData$DFB, toupper(keys))

where 2: prepareData(dfa, dfb, keys, trimChars)

where 3: processFlow(coercedData[[1]], coercedData[[2]], roundDigits, 

    keys, mismatches, trimChars, argsIn)

where 4 at testthat/testCheckPrintObject.R#214: rCompare(df_empty, df_empty, keys = c("ColA", "ColB"))

where 5: eval(code, test_env)

where 6: eval(code, test_env)

where 7: withCallingHandlers({

    eval(code, test_env)

    if (!handled && !is.null(test)) {

        skip_empty()

    }

}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning, 

    message = handle_message, error = handle_error)

where 8: doTryCatch(return(expr), name, parentenv, handler)

where 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])

where 10: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])

where 11: doTryCatch(return(expr), name, parentenv, handler)

where 12: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), 

    names[nh], parentenv, handlers[[nh]])

where 13: tryCatchList(expr, classes, parentenv, handlers)

where 14: tryCatch(withCallingHandlers({

    eval(code, test_env)

    if (!handled && !is.null(test)) {

        skip_empty()

    }

}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning, 

    message = handle_message, error = handle_error), error = handle_fatal, 

    skip = function(e) {

    })

where 15: test_code(desc, code, env = parent.frame())

where 16 at testthat/testCheckPrintObject.R#201: test_that("test print with two empty data frames", {

    df_empty <- data.frame(ColA = character(), ColB = as.Date(character()), 

        ColC = character(), stringsAsFactors = FALSE)

    comp1 <- rCompare(df_empty, df_empty)

    comp2 <- rCompare(df_empty, df_empty, keys = "ColA")

    comp3 <- rCompare(df_empty, df_empty, keys = c("ColA", "ColB"))

    comp4 <- rCompare(df_empty, df_empty, keys = c("ColA", "ColB", 

        "ColC"))

    text1 <- capture.output(print(comp1))

    text2 <- capture.output(print(comp2))

    text3 <- capture.output(print(comp3))

    text4 <- capture.output(print(comp4))

    expect_true(length(text1) == 2)

    expect_true(any(grepl("All columns were compared,  no rows compared because at least one table has no rows", 

        text1, fixed = TRUE)))

    expect_true(any(grepl("No variables match", text1, fixed = TRUE)))

    expect_true(length(text2) == 2)

    expect_true(any(grepl("All columns were compared,  no rows compared because at least one table has no rows", 

        text2, fixed = TRUE)))

    expect_true(any(grepl("No variables match", text2, fixed = TRUE)))

    expect_true(length(text3) == 2)

    expect_true(any(grepl("All columns were compared,  no rows compared because at least one table has no rows", 

        text3, fixed = TRUE)))

    expect_true(any(grepl("No variables match", text3, fixed = TRUE)))

    expect_true(length(text4) == 2)

    expect_true(any(grepl("All columns were compared,  no rows compared because at least one table has no rows", 

        text4, fixed = TRUE)))

    expect_true(any(grepl("No variables match", text4, fixed = TRUE)))

})

where 17: eval(code, test_env)

where 18: eval(code, test_env)

where 19: withCallingHandlers({

    eval(code, test_env)

    if (!handled && !is.null(test)) {

        skip_empty()

    }

}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning, 

    message = handle_message, error = handle_error)

where 20: doTryCatch(return(expr), name, parentenv, handler)

where 21: tryCatchOne(expr, names, parentenv, handlers[[1L]])

where 22: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])

where 23: doTryCatch(return(expr), name, parentenv, handler)

where 24: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), 

    names[nh], parentenv, handlers[[nh]])

where 25: tryCatchList(expr, classes, parentenv, handlers)

where 26: tryCatch(withCallingHandlers({

    eval(code, test_env)

    if (!handled && !is.null(test)) {

        skip_empty()

    }

}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning, 

    message = handle_message, error = handle_error), error = handle_fatal, 

    skip = function(e) {

    })

where 27: test_code(NULL, exprs, env)

where 28: source_file(path, new.env(parent = env), chdir = TRUE, wrap = wrap)

where 29: force(code)

where 30: doWithOneRestart(return(expr), restart)

where 31: withOneRestart(expr, restarts[[1L]])

where 32: withRestarts(testthat_abort_reporter = function() NULL, force(code))

where 33: with_reporter(reporter = reporter, start_end_reporter = start_end_reporter, 

    {

        reporter$start_file(basename(path))

        lister$start_file(basename(path))

        source_file(path, new.env(parent = env), chdir = TRUE, 

            wrap = wrap)

        reporter$.end_context()

        reporter$end_file()

    })

where 34: FUN(X[[i]], ...)

where 35: lapply(paths, test_file, env = env, reporter = current_reporter, 

    start_end_reporter = FALSE, load_helpers = FALSE, wrap = wrap)

where 36: force(code)

where 37: doWithOneRestart(return(expr), restart)

where 38: withOneRestart(expr, restarts[[1L]])

where 39: withRestarts(testthat_abort_reporter = function() NULL, force(code))

where 40: with_reporter(reporter = current_reporter, results <- lapply(paths, 

    test_file, env = env, reporter = current_reporter, start_end_reporter = FALSE, 

    load_helpers = FALSE, wrap = wrap))

where 41: test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure, 

    stop_on_warning = stop_on_warning, wrap = wrap)

where 42: test_dir(path = test_path, reporter = reporter, env = env, filter = filter, 

    ..., stop_on_failure = stop_on_failure, stop_on_warning = stop_on_warning, 

    wrap = wrap)

where 43: test_package_dir(package = package, test_path = test_path, filter = filter, 

    reporter = reporter, ..., stop_on_failure = stop_on_failure, 

    stop_on_warning = stop_on_warning, wrap = wrap)

where 44: test_check("dataCompareR")

 --- value of length: 2 type: logical ---

[1] FALSE FALSE

 --- function from context --- 

function (df_a, df_b, indices = NA) 

{

    if (length(indices == 1) && is.na(indices)) {

        return(matchNoIndex(df_a, df_b))

    }

    if (length(indices) == 1) {

        return(matchSingleIndex(df_a, df_b, indices))

    }

    if (length(indices) > 1) {

        return(matchMultiIndex(df_a, df_b, indices))

    }

}
```

</details>

**Comment by KrishanBhasin** [comment]
I'll reopen once I figure out why its failing

**Comment by KrishanBhasin** [comment]
It appears to be something to do with `matchRows()`, but I can't recreate the failure locally

**Comment by KrishanBhasin** [comment]
https://github.com/mailund/pmatch/issues/65 makes it look like its related to `matchRows()` use of `&&`?
Specifically:
```R
matchRows <- function(df_a, df_b, indices = NA)
{
  
  if (length(indices ==1) && is.na(indices)) { # This use of `&&` ?
    return(matchNoIndex(df_a, df_b))
  }

# more code, cut for brevity
}
```

**Comment by KrishanBhasin** [comment]
According to [this comment](https://github.com/mailund/pmatch/issues/65#issuecomment-460972778):
> 
> 
> See [R-devel version of R Internals](https://cran.r-project.org/doc/manuals/r-devel/R-ints.html), where the following seems to have appeared:
> 
> _R_CHECK_LENGTH_1_CONDITION_
> 
> ```
> Optionally check if the condition in if and while statements has length greater than one. For a true value (‘T’, ‘True’, ‘TRUE’ or ‘true’), give an error. For a false value (‘F’, ‘False’, ‘FALSE’ or ‘false’) or when unset, print a warning. Any other non-true non-empty value needs to be a list of commands separated by comma: ‘abort’ causes R to terminate unconditionally instead of signalling an error, ‘verbose’ prints very detailed diagnostic message, ‘package:pkg’ restricts the check to if/while statements executing in the namespace of package ‘pkg’, ‘package:_R_CHECK_PACKAGE_NAME_’ restricts the check to if/while statements executing in the package that is currently being checked by R CMD check, ‘warn’ causes R to report a warning instead of signalling an error. Default: unset (warning is reported)
> ```
> 
> _R_CHECK_LENGTH_1_LOGIC2_
> 
> ```
> Optionally check if either argument of the binary operators && and || has length greater than one. The format is the same as for _R_CHECK_LENGTH_1_CONDITION_. Default: unset (nothing is reported)
> ```

I don't have enough of the context for this function to know if swapping out `&&` for `&` beyond `&&` shortcuts and `&` returns a vector (I think?)

@sajohnston Could you verify if the changes to `matchRows()`  break any of the underlying intent for the function/how its used?

**Comment by sajohnston** [comment]
The problem isn't the `&&` but rather what is being passed to `&&`.  The `is.na` is likely returning a vector of logicals, rather than a single logical, which new(er) R guidelines now require. In older versions of R, it would look at the first item in the vector and evaluate it based on that, but now it errors if there are multiples. 

What we should probably do is move the `is.na` check into the single `if (length(indices == 1)`  condition block below.

**Comment by KrishanBhasin** [comment]
Code changed, tests pass & reporting from Travis is successful! 😄

**Pull request merged**
