### PR TITLE
Fix dplyr funs

### PR DESCRIPTION
**Pull request by sclewis23**
Fix dplyr::funs deprecated warning

## Description
Remove dplyr::funs which is deprecated 

## Motivation and Context
[https://github.com/capitalone/dataCompareR/issues/87](url)

## How Has This Been Tested?
Not tested

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sajohnston** [comment]
Thank you for your changes, @sclewis23 !

With the holidays, we're not in the office at the moment, but we'll take a look when we're back.

**Comment by sajohnston** [comment]
I've done a brief review, but it seems that many tests are failing due to columns in the data set being seen as functions, so I think this will require a more in-depth review to understand what is happening and how we might be able to fix it. I will prioritize that this week.

**Comment by KrishanBhasin** [comment]
Hey @sclewis23, thank you for raising this.

It looks like the CI is having issues building the package and running the CRAN checks; as @sajohnston said, it looks like there’s somewhere that the column name is being interpreted as a function.

Is this something you would be able to dig into so we can get this PR merged in?

**Comment by sclewis23** [comment]
Sure I'll take a look.

**Comment by sclewis23** [comment]
I updated the code and ran the test...now all I see are warnings about deprecated functions in dplyr.
Can you check the pull request now?

**Comment by sclewis23** [comment]
@KrishanBhasin - Sorry for the slow response, but I have update the code and it is passing test on my end.

**Comment by sajohnston** [comment]
Hi @sclewis23 
Thanks for the update. I will start taking a look at this this afternoon.

**Comment by KrishanBhasin** [comment]
Good morning @sclewis23!

Thank you for persisting with this.
For legal reasons we require the `CLAassistant` to be happy with each PR before we merge it. It looks like your most recent commit isn’t associated with the GitHub user that you to signed the CLA with, so the bot isn’t happy - it looks like the commit isn't associated with any user.

Are you able to roll back to the commit 19ba4b7f815ef4f230aa4c856bc851ac79c76888 , and then reapply your most recent change while associating your username with the commits?

You should be able to do this either by using GitHub’s UI to make the changes, or by setting up your local git config to associate with your GitHub account.

If you need any help with doing that please just let me know.

**Comment by sclewis23** [comment]
Ok, I think I finally got it...sorry had issue with the revert.

**Comment by KrishanBhasin** [comment]
It looks like https://github.com/capitalone/dataCompareR/pull/117/commits/ff35e19d51ecc4a69d10e11bf6dd9ae943a8dbfe is still in the commit history, so the CLAassistant isn't happy.

I can think of two solutions. Either:
- Create a new branch from `master`, apply all the changes to there using your GitHub account, and then we can merge that PR in
or
- Rewrite history for this branch
  1. Reset this branch to https://github.com/capitalone/dataCompareR/pull/117/commits/19ba4b7f815ef4f230aa4c856bc851ac79c76888 using `git reset --hard 19ba4b7f815ef4f230aa4c856bc851ac79c76888`
  2. Apply the changes back to this branch while associated to your GitHub user
  3. Push the changes up (this will need to be a force push as you will be rewriting history): `git push -f fix_dplyr_funs`

The latter option runs the risk of changes being lost if you force push before you've migrated all the changes over, so just take care if you're going to try that one.

**Comment by KrishanBhasin** [comment]
Yep that looks great! Thank you for persisting with it; once @sajohnston is happy with the change we can get this merged and released to the CRAN 🚢

**Review by sajohnston — APPROVED** [review]

**Comment by sajohnston** [comment]
Thanks so much for your contribution, @sclewis23 ! I will work on getting this to the CRAN this week.

**Comment by sclewis23** [comment]
@sajohnston - any update on the CRAN release ?

**Comment by sajohnston** [comment]
Hi @sclewis23 - I've started the release prep work but haven't had a chance to submit it yet. I will let you know once I've submitted it for review.

**Comment by sajohnston** [comment]
Hi @sclewis23 - I've submitted the package to the CRAN. It will still have to go through some checks on their end before it is live, but hopefully that shouldn't be too much longer.

**Comment by sajohnston** [comment]
Hi @sclewis23 - Apologies the CRAN submission got delayed because of a missed email. I will re-submit it this weekend.

**Comment by sclewis23** [comment]
Hi @sajohnston - just wanted follow-up and see how the CRAN submit was going....I know that can be a process.

**Comment by sajohnston** [comment]
It's been officially submitted now after trying to fix some things with the checks (and I did not miss the link this time!) - Hopefully it will be up in the next few days.

**Comment by sajohnston** [comment]
@sclewis23 It's on the CRAN now, finally! Apologies again for the delays. Thanks for your contributions!

**Pull request merged**
